import { walsheimPro } from "@/lib/font";
import { StickyBanner } from "@/components/ui/sticky-banner";
import { Toaster } from "@/components/ui/sonner";

import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="nl" suppressHydrationWarning className={walsheimPro.className}>
      <body className="min-h-screen scroll-smooth">
        <StickyBanner />
        <main className="h-full flex w-full flex-col">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
