import { walsheimPro } from "@/lib/font";
import { StickyBanner } from "@/components/ui/sticky-banner";
import { Toaster } from "@/components/ui/sonner";
import { GoogleAnalytics } from "@/components/analytics/google-analytics";
import { Suspense } from "react";

import "./globals.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Suspense fallback={<>...</>}>
      <html
        lang="nl"
        suppressHydrationWarning
        className={walsheimPro.className}
      >
        <GoogleAnalytics
          GA_TRACKING_ID={process.env.GA_TRACKING_ID as string}
        />
        <body className="min-h-screen bg-background antialiased">
          <StickyBanner />
          <main>{children}</main>
          <Toaster />
        </body>
      </html>
    </Suspense>
  );
}
